# Generated by Django 5.0.14 on 2026-07-07 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True)),
                ('participant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referral_link', to='users.participant')),
            ],
        ),
        migrations.CreateModel(
            name='ReferralLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=255)),
                ('client_phone', models.CharField(max_length=32)),
                ('status', models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В работе'), ('ordered', 'Клиент оформил заказ'), ('bonus_confirmed', 'Бонус подтверждён'), ('rejected', 'Отказ / не состоялось')], default='new', max_length=32)),
                ('admin_comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('referral_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='referrals.referrallink')),
            ],
        ),
    ]
