# Generated by Django 5.0.14 on 2026-07-11 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("referrals", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="referrallead",
            name="client_company",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
