# Generated by Django 5.0.14 on 2026-07-13 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0002_referrallead_client_company'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='referrallead',
            options={'verbose_name': 'Реферальная заявка', 'verbose_name_plural': 'Реферальные заявки'},
        ),
        migrations.AlterModelOptions(
            name='referrallink',
            options={'verbose_name': 'Реферальная ссылка', 'verbose_name_plural': 'Реферальные ссылки'},
        ),
        migrations.AlterField(
            model_name='referrallead',
            name='status',
            field=models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В работе'), ('ordered', 'Ожидает подтверждения'), ('bonus_confirmed', 'Бонус начислен'), ('rejected', 'Отклонена')], default='new', max_length=32),
        ),
    ]
