# Generated by Django 5.0.14 on 2026-07-15 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0003_alter_referrallead_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='referrallead',
            name='budget',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='referrallead',
            name='client_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='referrallead',
            name='client_position',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='referrallead',
            name='deadline',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='referrallead',
            name='product_interest',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='referrallead',
            name='quantity',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='referrallead',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
    ]
