# Generated by Django 5.0.14 on 2026-07-16 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0004_referrallead_budget_referrallead_client_email_and_more'),
        ('users', '0004_alter_participant_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referrallead',
            name='admin_comment',
            field=models.TextField(blank=True, verbose_name='Комментарий администратора'),
        ),
        migrations.AlterField(
            model_name='referrallead',
            name='budget',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Бюджет'),
        ),
        migrations.AlterField(
            model_name='referrallead',
            name='client_company',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Компания клиента'),
        ),
        migrations.AlterField(
            model_name='referrallead',
            name='client_email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='Email клиента'),
        ),
        migrations.AlterField(
            model_name='referrallead',
            name='client_name',
            field=models.CharField(max_length=255, verbose_name='Имя клиента'),
        ),
        migrations.AlterField(
            model_name='referrallead',
            name='client_phone',
            field=models.CharField(max_length=32, verbose_name='Телефон клиента'),
        ),
        migrations.AlterField(
            model_name='referrallead',
            name='client_position',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Должность клиента'),
        ),
        migrations.AlterField(
            model_name='referrallead',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='referrallead',
            name='deadline',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Срок'),
        ),
        migrations.AlterField(
            model_name='referrallead',
            name='product_interest',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Интерес к продукции'),
        ),
        migrations.AlterField(
            model_name='referrallead',
            name='quantity',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Тираж'),
        ),
        migrations.AlterField(
            model_name='referrallead',
            name='referral_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='referrals.referrallink', verbose_name='Реферальная ссылка'),
        ),
        migrations.AlterField(
            model_name='referrallead',
            name='rejection_reason',
            field=models.TextField(blank=True, verbose_name='Причина отказа'),
        ),
        migrations.AlterField(
            model_name='referrallead',
            name='status',
            field=models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В работе'), ('ordered', 'Ожидает подтверждения'), ('bonus_confirmed', 'Бонус начислен'), ('rejected', 'Отклонена')], default='new', max_length=32, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='referrallink',
            name='code',
            field=models.CharField(max_length=64, unique=True, verbose_name='Код ссылки'),
        ),
        migrations.AlterField(
            model_name='referrallink',
            name='participant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referral_link', to='users.participant', verbose_name='Участник'),
        ),
    ]
