# Generated by Django 5.0.14 on 2026-07-11 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="participant",
            name="company",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="participant",
            name="position",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="participant",
            name="is_primary_contact",
            field=models.BooleanField(default=False),
        ),
    ]
