# Generated by Django 5.0.14 on 2026-07-13 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_participant_company_position_primary'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='participant',
            options={'verbose_name': 'Участник', 'verbose_name_plural': 'Участники'},
        ),
    ]
