# Generated by Django 5.0.14 on 2026-07-16 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_participant_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='company',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Компания'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='consent_accepted',
            field=models.BooleanField(default=False, verbose_name='Согласие получено'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='full_name',
            field=models.CharField(max_length=255, verbose_name='Участник'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='is_primary_contact',
            field=models.BooleanField(default=False, verbose_name='Основной контакт'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='phone',
            field=models.CharField(max_length=32, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='position',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='telegram_id',
            field=models.CharField(max_length=64, unique=True, verbose_name='Telegram ID'),
        ),
    ]
