# Generated by Django 5.0.14 on 2026-07-10 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bonuses", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bonusspendrequest",
            name="comment",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
