# Generated by Django 5.0.14 on 2026-07-13 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bonuses', '0003_alter_bonusspendrequest_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bonusledgerentry',
            options={'verbose_name': 'Начисление бонусов', 'verbose_name_plural': 'Начисления бонусов'},
        ),
        migrations.AlterModelOptions(
            name='bonusspendrequest',
            options={'verbose_name': 'Запрос на списание бонусов', 'verbose_name_plural': 'Запросы на списание бонусов'},
        ),
    ]
