# Generated by Django 5.0.14 on 2026-07-15 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonuses', '0004_alter_bonusledgerentry_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonusledgerentry',
            name='entry_type',
            field=models.CharField(choices=[('accrual', 'Начисление'), ('reversal', 'Аннулирование'), ('expiration', 'Сгорание'), ('manual_adjustment', 'Ручная корректировка')], default='accrual', max_length=32),
        ),
        migrations.AddField(
            model_name='bonusledgerentry',
            name='expires_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
