# Generated by Django 5.0.14 on 2026-07-16 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonuses', '0006_bonusledgerentry_expiration_warning_sent_at'),
        ('referrals', '0005_alter_referrallead_admin_comment_and_more'),
        ('users', '0004_alter_participant_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonusledgerentry',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='bonusledgerentry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='bonusledgerentry',
            name='entry_type',
            field=models.CharField(choices=[('accrual', 'Начисление'), ('reversal', 'Аннулирование'), ('expiration', 'Сгорание'), ('manual_adjustment', 'Ручная корректировка')], default='accrual', max_length=32, verbose_name='Тип операции'),
        ),
        migrations.AlterField(
            model_name='bonusledgerentry',
            name='expiration_warning_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Предупреждение отправлено'),
        ),
        migrations.AlterField(
            model_name='bonusledgerentry',
            name='expires_at',
            field=models.DateField(blank=True, null=True, verbose_name='Сгорает'),
        ),
        migrations.AlterField(
            model_name='bonusledgerentry',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bonus_entries', to='referrals.referrallead', verbose_name='Реферальная заявка'),
        ),
        migrations.AlterField(
            model_name='bonusledgerentry',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonus_entries', to='users.participant', verbose_name='Участник'),
        ),
        migrations.AlterField(
            model_name='bonusledgerentry',
            name='reason',
            field=models.CharField(max_length=255, verbose_name='Основание'),
        ),
        migrations.AlterField(
            model_name='bonusspendrequest',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='bonusspendrequest',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Подарок или комментарий'),
        ),
        migrations.AlterField(
            model_name='bonusspendrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='bonusspendrequest',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spend_requests', to='users.participant', verbose_name='Участник'),
        ),
        migrations.AlterField(
            model_name='bonusspendrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'На рассмотрении'), ('approved', 'Подтверждена'), ('rejected', 'Отклонена')], default='pending', max_length=32, verbose_name='Статус'),
        ),
    ]
